# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_components
#' @noRd 
rcpp_boundary <- function(image) {
    .Call(`_mapscanner_rcpp_boundary`, image)
}

#' rcpp_components
#' @noRd 
rcpp_components <- function(image) {
    .Call(`_mapscanner_rcpp_components`, image)
}

#' rcpp_concaveman
#' @noRd 
rcpp_concaveman <- function(xy, hull_in, concavity, lengthThreshold) {
    .Call(`_mapscanner_rcpp_concaveman`, xy, hull_in, concavity, lengthThreshold)
}

#' rcpp_edge_thin
#' @noRd 
rcpp_edge_thin <- function(image) {
    .Call(`_mapscanner_rcpp_edge_thin`, image)
}

